/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "textlint",
  "tagline": "The pluggable linting tool for text and markdown",
  "url": "https://textlint.github.io",
  "baseUrl": "/",
  "organizationName": "textlint",
  "projectName": "textlint",
  "scripts": [
    "https://buttons.github.io/buttons.js"
  ],
  "favicon": "img/textlint-icon_256x256.png",
  "customFields": {
    "users": [
      {
        "caption": "JavaScript Primer",
        "image": "https://78.media.tumblr.com/avatar_c63524fcb991_128.png",
        "infoLink": "https://jsprimer.net",
        "pinned": true
      },
      {
        "caption": "jp.vuejs.org",
        "image": "https://avatars3.githubusercontent.com/u/6128107?s=200&v=4",
        "infoLink": "https://github.com/vuejs/jp.vuejs.org",
        "pinned": true
      },
      {
        "caption": "SURVIVEJS - WEBPACK",
        "image": "https://www.gravatar.com/avatar/b26ec3c2769168c2cbc64cc3df9cdd9c?s=200",
        "infoLink": "https://survivejs.com/webpack/",
        "pinned": true
      },
      {
        "caption": "Hoodie",
        "image": "https://hoodiehq.github.io/hoodie-css/src/content_img/animals/low-profile-dog-3.png",
        "infoLink": "http://hood.ie/",
        "pinned": true
      },
      {
        "caption": "GIS実習オープン教材",
        "image": "https://raw.githubusercontent.com/gis-oer/gis-oer/master/img/logo/logo_gis-oer_01_256px.png",
        "infoLink": "https://github.com/gis-oer/gis-oer",
        "pinned": true
      },
      {
        "caption": "株式会社ソラコム",
        "image": "/img/soracom.png",
        "infoLink": "https://soracom.jp",
        "pinned": true
      },
      {
        "caption": "校正さん",
        "image": "https://kohsei-san.hata6502.com/favicon.png",
        "infoLink": "https://kohsei-san.hata6502.com/lp/",
        "pinned": true
      }
    ],
    "repoUrl": "https://github.com/textlint/textlint"
  },
  "onBrokenLinks": "log",
  "onBrokenMarkdownLinks": "log",
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "showLastUpdateAuthor": true,
          "showLastUpdateTime": true,
          "editUrl": "https://github.com/textlint/textlint/edit/master/docs/",
          "path": "../docs",
          "sidebarPath": "../website/sidebars.json"
        },
        "blog": {
          "path": "blog"
        },
        "theme": {
          "customCss": [
            "/src/css/customTheme.css",
            "/src/css/custom.css"
          ]
        }
      }
    ]
  ],
  "plugins": [
    [
      "@docusaurus/plugin-client-redirects",
      {
        "fromExtensions": [
          "html"
        ]
      }
    ]
  ],
  "themeConfig": {
    "navbar": {
      "title": "textlint",
      "logo": {
        "src": "img/textlint-icon_256x256.png"
      },
      "items": [
        {
          "to": "docs/getting-started",
          "label": "Docs",
          "position": "left"
        },
        {
          "href": "https://github.com/textlint/textlint/wiki/Collection-of-textlint-rule",
          "label": "Rules",
          "position": "left"
        },
        {
          "to": "blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "to": "/help",
          "label": "Help",
          "position": "left"
        },
        {
          "href": "https://github.com/textlint/textlint",
          "label": "GitHub",
          "position": "left"
        }
      ],
      "hideOnScroll": false
    },
    "image": "img/textlint-icon_256x256.png",
    "footer": {
      "links": [],
      "copyright": "Copyright © 2024textlint organization",
      "logo": {
        "src": "img/textlint-icon_256x256.png"
      },
      "style": "light"
    },
    "algolia": {
      "appId": "BH4D9OD16A",
      "apiKey": "27ef1d5fc0d12142485f3784f7d3cb46",
      "indexName": "textlint",
      "algoliaOptions": {},
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "themes": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
